@{
    # Module manifest generated by ZRR PowerShell Module Creator
    RootModule = 'ZRR.Terraform.Wrapper.psm1'
    ModuleVersion = '0.1.0'
    CompatiblePSEditions = @('Desktop', 'Core')
    GUID = '56a24603-83a5-4b54-8f26-36c2e7d7cc12'

    Author = 'Zealous Rock Research'
    CompanyName = 'ZRR'
    Copyright = '(c) 2025 Zealous Rock Research. All rights reserved.'

    Description = 'Enterprise-grade Terraform workflow automation and management wrapper with advanced pipeline integration, state management, and cross-platform deployment capabilities.'
    PowerShellVersion = '5.1'

    # Dependencies
    RequiredModules = @()

    # Functions to export
    FunctionsToExport = @(
        'Invoke-TerraformInit',
        'Invoke-TerraformPlan',
        'Invoke-TerraformApply',
        'Invoke-TerraformDestroy',
        'Get-TerraformState',
        'Set-TerraformWorkspace',
        'New-TerraformWorkspace',
        'Remove-TerraformWorkspace',
        'Test-TerraformConfiguration',
        'Get-TerraformOutput',
        'Import-TerraformResource',
        'Export-TerraformState',
        'Backup-TerraformState',
        'Restore-TerraformState',
        'Invoke-TerraformValidate',
        'Format-TerraformConfiguration',
        'Get-TerraformProvider',
        'Update-TerraformProvider',
        'New-TerraformModule',
        'Test-TerraformCompliance',
        'Invoke-TerraformRefresh',
        'Get-TerraformResource',
        'Move-TerraformResource',
        'Remove-TerraformResource',
        'Protect-TerraformResource',
        'Unprotect-TerraformResource'
    )

    # Variables to export
    VariablesToExport = @()

    # Aliases to export
    AliasesToExport = @(
        'tf-init',
        'tf-plan',
        'tf-apply',
        'tf-destroy',
        'tf-state',
        'tf-workspace',
        'tf-validate',
        'tf-fmt',
        'tf-refresh',
        'tf-import'
    )

    # Cmdlets to export
    CmdletsToExport = @()

    # Private data
    PrivateData = @{
        PSData = @{
            # Tags for PowerShell Gallery
            Tags = @('ZRR', 'Terraform', 'Infrastructure', 'IaC', 'DevOps', 'Automation', 'Enterprise', 'Utility')

            # License and project URLs
            LicenseUri = 'https://github.com/zealous-rock-research/zrr-ps-module-lib/blob/main/LICENSE'
            ProjectUri = 'https://github.com/zealous-rock-research/zrr-ps-module-lib'
            IconUri = 'https://raw.githubusercontent.com/zealous-rock-research/branding/main/icons/terraform-powershell.png'

            # Release notes
            ReleaseNotes = 'Initial release of ZRR.Terraform.Wrapper module with enterprise features including workspace management, advanced state handling, pipeline integration, and comprehensive error handling.'

            # External module dependencies
            ExternalModuleDependencies = @()

            # Prerelease string
            # Prerelease = 'alpha'
        }
    }

    # Help info
    HelpInfoURI = 'https://docs.zealousrock.dev/powershell/ZRR.Terraform.Wrapper'
}