@{
    # Module manifest generated by ZRR PowerShell Module Creator
    RootModule = 'ZRR.Research.EntrezUtilities.psm1'
    ModuleVersion = '0.1.0'
    CompatiblePSEditions = @('Desktop', 'Core')
    GUID = 'a7b2c3d4-e5f6-4a5b-9c8d-7e6f5a4b3c2d'

    Author = 'Zealous Rock Research'
    CompanyName = 'ZRR'
    Copyright = '(c) 2025 Zealous Rock Research. All rights reserved.'

    Description = 'ZRR Research module for accessing NCBI Entrez Programming Utilities (E-utilities) with enterprise-grade logging, error handling, and comprehensive API coverage for scientific research data retrieval.'
    PowerShellVersion = '5.1'

    # Dependencies
    RequiredModules = @(
        @{
            ModuleName = 'PSFramework'
            ModuleVersion = '1.7.249'
        }
    )

    # Functions to export - Auto-populated from Public/ folder
    FunctionsToExport = @(
        'Search-Entrez',
        'Search-EntrezDatabase',
        'Get-EntrezDocumentSummary',
        'Get-EntrezDataRecord',
        'Get-EntrezPubMedArticle',
        'Get-EntrezProteinSequence',
        'Get-EntrezNucleotideSequence',
        'Search-EntrezAdvanced',
        'Export-EntrezResults',
        'Clear-EntrezSession',
        'Set-EntrezApiKey',
        'Get-EntrezSession'
    )

    # Variables to export
    VariablesToExport = @()

    # Aliases to export
    AliasesToExport = @(
        'Get-EntrezSummary',
        'Get-EntrezData'
    )

    # Cmdlets to export
    CmdletsToExport = @()

    # Private data
    PrivateData = @{
        PSData = @{
            # Tags for PowerShell Gallery (≤10 limit)
            Tags = @('ZRR', 'Research', 'NCBI', 'Entrez', 'Bioinformatics', 'PubMed', 'API', 'Science', 'Data', 'Enterprise')

            # License and project URLs
            LicenseUri = 'https://github.com/zealous-rock-research/zrr-ps-module-lib/blob/main/LICENSE'
            ProjectUri = 'https://github.com/zealous-rock-research/zrr-ps-module-lib'
            IconUri = 'https://raw.githubusercontent.com/zealous-rock-research/branding/main/icons/powershell-module.png'

            # Release notes
            ReleaseNotes = @'
Initial release of ZRR.Research.EntrezUtilities module

Features:
- Complete NCBI Entrez E-utilities API coverage (ESearch, ESummary, EFetch)
- Enterprise-grade logging with PSFramework integration
- Comprehensive error handling and validation
- Session management with history server support
- Batch processing capabilities for large datasets
- Multi-format export functionality (JSON, XML, CSV, TXT)
- Specialized functions for PubMed, Protein, and Nucleotide databases
- Cross-platform compatibility (Windows, Linux, macOS)
- Full Pester test coverage with CI/CD integration
- PowerShell Gallery compliance with security scanning
'@

            # External module dependencies
            ExternalModuleDependencies = @('PSFramework')

            # Prerelease string
            # Prerelease = 'alpha'
        }
    }

    # Help info
    HelpInfoURI = 'https://docs.zealousrock.dev/powershell/ZRR.Research.EntrezUtilities'
}